export const PATH_NAME = {
  ROOT: "/",
  ERROR_404: "/404",
  //   DASHBOARD: '/dashboard',
  PLAY_BACKGROUND: "/playbackground",
  LOGIN: "/login",
  PRODUCT: "/product",
  CART: "/cart",
  CHAT: "/chat",
  TEST: "/test",
  PAYMENT: "/payment",
  PRODUCT_LIST: "/product/list",
  PRODUCT_ADD: "/product/add",
  USERS: "/users",
  KANBAN: "/kanban",
  NOTFOUND: "/notfound",
};
